package com.felipemz.inventaryapp.ui.product_form.components

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Row
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.Delete
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.SpanStyle
import androidx.compose.ui.text.buildAnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.text.withStyle
import com.felipemz.inventaryapp.R
import com.felipemz.inventaryapp.core.extensions.ifFalse

@Composable
internal fun IdProductField(
    modifier: Modifier,
    idProduct: Int?,
    isNewProduct: Boolean,
    action: () -> Unit,
) {
    Row(
        modifier = modifier,
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween
    ) {
        Text(
            text = getIdString(idProduct),
            fontWeight = FontWeight.Bold,
        )

        isNewProduct.ifFalse {
            IconButton(onClick = action) {
                Icon(
                    imageVector = Icons.Rounded.Delete,
                    tint = MaterialTheme.colorScheme.error,
                    contentDescription = null
                )
            }
        }
    }
}

@Composable
private fun getIdString(id: Int?) = buildAnnotatedString {
    append(stringResource(R.string.copy_id_dots))
    withStyle(
        style = SpanStyle(
            fontWeight = FontWeight.Light,
            textDecoration = TextDecoration.Underline,
            color = MaterialTheme.colorScheme.outline
        ),
    ) {
        append(
            id?.toString()?.padStart(
                length = 6,
                padChar = '0'
            ) ?: stringResource(R.string.copy_autogenerated)
        )
    }
}